# 13City站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "13City"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  source: "processing_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    source:
      source_key: "区域"

  title_components:
    title:
      source_key: "主标题"
    season_episode:
      source_key: "季集"
    year:
      source_key: "年份"
    status:
      source_key: "剧集状态"
    edition:
      source_key: "发布版本"
    resolution:
      source_key: "分辨率"
    platform:
      source_key: "片源平台"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    video_format:
      source_key: "视频格式"
    hdr_format:
      source_key: "HDR格式"
    bit_depth:
      source_key: "色深"
    frame_rate:
      source_key: "帧率"
    audio_codec:
      source_key: "音频编码"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "电影": "category.movie"
      "电视剧": "category.tv_series"
      "综艺": "category.tv_shows"
      "动漫": "category.animation"
      "MV": "category.music_video"
      "音乐": "category.music"
      "电子书": "category.ebook"
      "纪录片": "category.documentaries"
      "其他": "category.other"

    medium:
      "Blu-ray": "medium.bluray"
      "BluRay": "medium.bluray"
      "UHD Blu-ray": "medium.uhd_bluray"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "MiniBD": "medium.minibd"
      "WEB-DL": "medium.webdl"
      "WEBRip": "medium.webrip"
      "HDTV": "medium.hdtv"
      "DVD": "medium.dvd"
      "DVDR": "medium.dvdr"
      "CD": "medium.cd"
      "Track": "medium.track"
      "Other": "medium.other"

    video_codec:
      "H.264/AVC": "video.h264"
      "H.265/HEVC": "video.h265"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "AV1": "video.av1"
      "VP9": "video.vp9"
      "Xvid": "video.xvid"
      "Other": "video.other"

    audio_codec:
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "DTS": "audio.dts"
      "DTS-HD": "audio.dts_hd_ma"
      "DTS-X": "audio.dtsx"
      "MP3": "audio.mp3"
      "OGG": "audio.ogg"
      "AAC": "audio.aac"
      "Other": "audio.other"
      "DD/AC3": "audio.ac3"
      "AC3": "audio.ac3"
      "TrueHD Atmos": "audio.truehd_atmos"
      "DDP/E-AC3": "audio.ddp"
      "E-AC3": "audio.ddp"
      "LPCM": "audio.lpcm"
      "TrueHD": "audio.truehd"
      "DTS:X": "audio.dtsx"
      "DTS-HD MA": "audio.dts_hd_ma"
      "M4A": "audio.m4a"
      "WAV": "audio.wav"

    resolution:
      "8K": "resolution.r8k"
      "4K": "resolution.r4k"
      "2160p": "resolution.r2160p"
      "1440p": "resolution.r1440p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "480p": "resolution.r480p"
      "Other": "resolution.other"

    team:
      "13City": "team.city13"
      "PTerWEB": "team.pterweb"
      "WiKi": "team.wiki"
      "UBits": "team.ubits"
      "ADWeb": "team.adweb"
      "ZmWeb": "team.zmweb"
      "UBWEB": "team.ubweb"
      "SewageWeb": "team.sewageweb"
      "Other": "team.other"
      "rainweb": "team.rainweb"
      "QHstudIo": "team.qhstudio"
      "MTeam": "team.mteam"
      "FRDS": "team.frds"
      "CHDWEB": "team.chdweb"
      "HHWEB": "team.hhweb"
      "52pt": "team.pt52"
      "AilMWeb": "team.ailmweb"

    source:
      "中国（含港澳台）": "source.china"
      "日本": "source.japan"
      "泰国": "source.thailand"
      "印度": "source.india"
      "韩国": "source.korea"
      "欧美": "source.western"
      "Other（其他）": "source.other"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.animation": "405"
    "category.music_video": "406"
    "category.music": "408"
    "category.ebook": "409"
    "category.documentaries": "413"
    "category.other": "401"
    "default": "401"

  medium:
    "medium.bluray": "1"
    "medium.uhd_bluray": "10"
    "medium.remux": "3"
    "medium.encode": "7"
    "medium.minibd": "4"
    "medium.webdl": "10"
    "medium.webrip": "12"
    "medium.hdtv": "5"
    "medium.dvd": "6"
    "medium.dvdr": "6"
    "medium.cd": "8"
    "medium.track": "9"
    "medium.other": "13"
    "default": "13"

  video_codec:
    "video.h264": "1"
    "video.h265": "2"
    "video.vc1": "4"
    "video.mpeg2": "3"
    "video.av1": "6"
    "video.vp9": "5"
    "video.xvid": "6"
    "video.other": "7"
    "default": "7"

  audio_codec:
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.dts": "3"
    "audio.mp3": "4"
    "audio.ogg": "5"
    "audio.aac": "6"
    "audio.other": "11"
    "audio.ac3": "7"
    "audio.truehd_atmos": "9"
    "audio.ddp": "7"
    "audio.lpcm": "10"
    "audio.truehd": "8"
    "audio.dtsx": "3"
    "audio.dts_hd_ma": "3"
    "audio.m4a": "11"
    "audio.wav": "11"
    "default": "11"

  resolution:
    "resolution.r8k": "1"
    "resolution.r4k": "2"
    "resolution.r2160p": "2"
    "resolution.r1440p": "5"
    "resolution.r1080p": "3"
    "resolution.r1080i": "4"
    "resolution.r720p": "5"
    "resolution.r480p": "5"
    "resolution.other": "5"
    "default": "5"

  source:
    "source.china": "1"
    "source.japan": "2"
    "source.thailand": "3"
    "source.india": "4"
    "source.korea": "5"
    "source.western": "6"
    "source.other": "7"
    "default": "7"

  team:
    "team.city13": "1"
    "team.ailmweb": "2"
    "team.pt52": "3"
    "team.hhweb": "4"
    "team.chdweb": "5"
    "team.frds": "6"
    "team.mteam": "7"
    "team.qhstudio": "8"
    "team.pterweb": "9"
    "team.rainweb": "10"
    "team.sewageweb": "12"
    "team.ubweb": "13"
    "team.zmweb": "14"
    "team.adweb": "15"
    "team.ubits": "16"
    "team.wiki": "17"
    "team.other": "11"
    "default": "11"

  tag:
    "禁转": 1
    "首发": 2
    "完结": 9
    "分集": 8
    "粤语": 13
    "多语": 10
    "国语": 5
    "中字": 6
    "中英双字": 14
    "4K": 12
    "1080p": 11
    "HDR": 7
    "DIY": 4
    "红叶转载": 19
    "有声图书": 15
    "default": null
