# RaingFH站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "RaingFH"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  title_components:
    title:
      source_key: "主标题"
    season_episode:
      source_key: "季集"
    year:
      source_key: "年份"
    status:
      source_key: "剧集状态"
    edition:
      source_key: "发布版本"
    resolution:
      source_key: "分辨率"
    platform:
      source_key: "片源平台"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    video_format:
      source_key: "视频格式"
    hdr_format:
      source_key: "HDR格式"
    bit_depth:
      source_key: "色深"
    frame_rate:
      source_key: "帧率"
    audio_codec:
      source_key: "音频编码"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "Movies": "category.movie"
      "电影": "category.movie"
      "TV Series": "category.tv_series"
      "电视剧": "category.tv_series"
      "Animations": "category.animation"
      "动漫": "category.animation"
      "动画": "category.animation"
      "TV Shows": "category.tv_shows"
      "综艺": "category.tv_shows"
      "Documentaries": "category.documentaries"
      "纪录片": "category.documentaries"
      "Sports": "category.sports"
      "体育": "category.sports"
      "Music Videos": "category.music_video"
      "音乐视频": "category.music_video"
      "HQ Audio": "category.music"
      "高品质音频": "category.music"
      "音乐": "category.music"
      "其他": "category.other"
      "Misc": "category.other"
      "未知": "category.other"
      "other": "category.other"

    medium:
      "UHD Blu-ray": "medium.uhd_bluray"
      "Blu-ray": "medium.bluray"
      "BD": "medium.bluray"
      "BluRay": "medium.bluray"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "MiniBD": "medium.minibd"
      "HDTV": "medium.hdtv"
      "DVDR": "medium.dvdr"
      "WEB-DL": "medium.webdl"
      "WEBRip": "medium.webrip"
      "WEB": "medium.webdl"
      "CD": "medium.cd"
      "Track": "medium.track"
      "HD DVD": "medium.hddvd"
      "Other": "medium.other"

    video_codec:
      "H.264": "video.h264"
      "AVC": "video.h264"
      "x264": "video.x264"
      "H.265": "video.h265"
      "HEVC": "video.h265"
      "x265": "video.x265"
      "MPEG-2": "video.mpeg2"
      "MPEG-4": "video.mpeg4"
      "XviD": "video.xvid"
      "VP9": "video.vp9"
      "VC-1": "video.vc1"
      "AV1": "video.av1"
      "Other": "video.other"

    audio_codec:
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "WAV": "audio.wav"
      "AAC": "audio.aac"
      "DTS": "audio.dts"
      "AC3": "audio.ac3"
      "DD": "audio.ac3"
      "DTS-HD": "audio.dts_hd_ma"
      "TrueHD": "audio.truehd"
      "LPCM": "audio.lpcm"
      "M4A": "audio.m4a"
      "MP3": "audio.mp3"
      "OGG": "audio.ogg"
      "Other": "audio.other"

    resolution:
      "8K": "resolution.r4320p"
      "4320p": "resolution.r4320p"
      "4K": "resolution.r2160p"
      "2160p": "resolution.r2160p"
      "1440p": "resolution.r1440p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "ED": "resolution.ed"
      "Other": "resolution.other"

    team:
      "Audies": "team.audies"
      "PTer": "team.pter"
      "OurBits": "team.ourbits"
      "HDS": "team.hds"
      "FRDS": "team.frds"
      "CMCT": "team.cmct"
      "beAst": "team.beast"
      "WiKi": "team.wiki"
      "TTG": "team.ttg"
      "BTN/NTb": "team.btn_ntb"
      "HHWEB": "team.hhweb"
      "Ubits": "team.ubits"
      "rainweb": "team.rainweb"
      "rain": "team.rain"
      "PTP": "team.ptp"
      "TLF": "team.tlf"
      "Hares": "team.hares"
      "QHstudIo": "team.qhstudio"
      "PTHome": "team.pthome"
      "HDHome": "team.hdhome"
      "HHClub": "team.hhclub"
      "Other": "team.other"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.animation": "405"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.sports": "407"
    "category.music_video": "406"
    "category.music": "408"
    "category.other": "410"
    "default": "410"

  medium:
    "medium.uhd_bluray": "1"
    "medium.bluray": "1"
    "medium.remux": "3"
    "medium.encode": "7"
    "medium.minibd": "4"
    "medium.hdtv": "5"
    "medium.dvdr": "6"
    "medium.webdl": "10"
    "medium.webrip": "7"
    "medium.cd": "8"
    "medium.track": "9"
    "medium.hddvd": "2"
    "medium.other": "11"
    "default": "11"

  video_codec:
    "video.h264": "1"
    "video.x264": "1"
    "video.h265": "2"
    "video.x265": "2"
    "video.mpeg2": "3"
    "video.mpeg4": "4"
    "video.xvid": "5"
    "video.vp9": "6"
    "video.vc1": "7"
    "video.av1": "8"
    "video.other": "9"
    "default": "9"

  audio_codec:
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.wav": "3"
    "audio.aac": "4"
    "audio.dts": "5"
    "audio.ac3": "6"
    "audio.dts_hd_ma": "7"
    "audio.truehd": "8"
    "audio.lpcm": "9"
    "audio.m4a": "10"
    "audio.mp3": "11"
    "audio.ogg": "12"
    "audio.other": "13"
    "default": "13"

  resolution:
    "resolution.r4320p": "8"
    "resolution.r2160p": "7"
    "resolution.r1440p": "6"
    "resolution.r1080p": "1"
    "resolution.r1080i": "2"
    "resolution.r720p": "3"
    "resolution.sd": "4"
    "resolution.ed": "5"
    "resolution.other": "9"
    "default": "9"

  team:
    "team.audies": "1"
    "team.pter": "11"
    "team.ourbits": "10"
    "team.hds": "9"
    "team.frds": "8"
    "team.cmct": "7"
    "team.beast": "6"
    "team.wiki": "5"
    "team.ttg": "4"
    "team.btn_ntb": "3"
    "team.hhweb": "22"
    "team.ubits": "13"
    "team.rainweb": "23"
    "team.rain": "24"
    "team.ptp": "20"
    "team.tlf": "19"
    "team.hares": "18"
    "team.qhstudio": "17"
    "team.pthome": "16"
    "team.hdhome": "15"
    "team.hhclub": "14"
    "team.other": "21"
    "default": "21"

  tag:
    "禁转": 1
    "首发": 2
    "DIY": 4
    "国语": 5
    "中字": 6
    "HDR": 7
    "default": null
