# Zmpt站点的配置文件
site_name: "Zmpt"
form_fields:
  medium: "medium_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "403"
    "综艺": "403"
    "Documentaries": "422"
    "记录片": "422"
    "纪录片": "422"
    "Animations": "417"
    "动漫": "417"
    "动画": "417"
    "Anime": "417"
    "Short Play": "427"
    "短剧": "427"
    "Music": "423"
    "音乐": "423"
    "专辑": "423"
    "音轨": "423"
    "音频": "423"
    "Audiobook": "424"
    "有声书": "424"
    "Software": "425"
    "软件": "425"
    "Game": "426"
    "游戏": "426"
    "其他": "409"
    "Misc": "409"
    "未知": "409"
    "Unknown": "409"
    "default": "409"

  medium:
    'UHD Blu-ray': '1'
    'Blu-ray': '1'
    'BD': '1'
    'Remux': '3'
    'Encode': '7'
    'WEB-DL': '10'
    'WEBRip': '7'
    'WEB': '10'
    'HDTV': '5'
    'TVrip': '5'
    'DVD': '6'
    'HD DVD': '2'
    'MiniBD': '4'
    'CD': '8'
    'Track': '8'
    'default': '12'

  resolution:
    '8K': '9'
    '4320p': '9'
    '4K': '5'
    '2160p': '5'
    'UHD': '5'
    '2K': '6'
    '1440p': '6'
    '1080p': '1'
    '1080i': '1'
    '720p': '8'
    '480p': '7'
    '480i': '7'
    'default': '1'

  audio_codec:
    'FLAC': '1'
    'APE': '2'
    'DTS': '3'
    'OGG': '5'
    'AC3': '8'
    'DD': '8'
    'AAC': '6'
    'MP3': '4'
    'ALAC': '9'
    'WAV': '10'
    'LPCM': '10'
    'default': '7'

  team:
    "ZmWeb": "7"
    "ZmPT": "6"
    "ZmMusic": "8"
    "ZmAudio": "11"
    "DYZ-Movie": "9"
    "GodDramas": "10"
    "RL/RL4B": "12"
    "RL": "12"
    "default": "5"

  tag:
    "驻站": 17
    "禁转": 1
    "国语": 5
    "粤语": 15
    "中字": 6
    "DIY": 4
    "杜比": 14
    "HDR": 7
    "无损": 16
    "首发": 2
    "短剧": 13
    "汉化": 11
    "原创": 9
    "完结": 12
    "分集": 8
    "纯享版": 18
    "default": null