# RainGFRain站点的配置文件
site_name: "RainGFRain"

form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "TV Shows": "403"
    "综艺": "403"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "Sports": "407"
    "体育": "407"
    "Music Videos": "406"
    "音乐视频": "406"
    "HQ Audio": "408"
    "高品质音频": "408"
    "Music": "408"
    "音乐": "408"
    "其他": "410"
    "Misc": "409"
    "未知": "410"
    "Unknown": "410"
    "default": "410"

  medium:
    'UHD Blu-ray': '1'
    'Blu-ray': '1'
    'BD': '1'
    'Remux': '3'
    'Encode': '7'
    'MiniBD': '4'
    'HDTV': '5'
    'DVDR': '6'
    'WEB-DL': '10'
    'WEBRip': '7'
    'WEB': '10'
    'CD': '8'
    'Track': '9'
    'HD DVD': '2'
    'Other': '11'
    'default': '11'

  codec:
    'H.264': '1'
    'AVC': '10'
    'x264': '1'
    'H.265': '2'
    'HEVC': '2'
    'x265': '2'
    'MPEG-2': '3'
    'MPEG-4': '4'
    'XviD': '5'
    'VP9': '6'
    'VC-1': '7'
    'AV1': '8'
    'Other': '9'
    'default': '9'

  audio_codec:
    'FLAC': '1'
    'APE': '2'
    'WAV': '3'
    'AAC': '4'
    'DTS': '5'
    'AC3': '6'
    'DD': '6'
    'DTS-HD': '7'
    'TrueHD': '8'
    'LPCM': '9'
    'M4A': '10'
    'MP3': '11'
    'OGG': '12'
    'Other': '13'
    'default': '13'

  resolution:
    '8K': '8'
    '4320p': '8'
    '4K': '7'
    '2160p': '7'
    'QHD': '6'
    '1440p': '6'
    'FHD': '1'
    '1080p': '1'
    '1080i': '2'
    'HD': '3'
    '720p': '3'
    'SD': '4'
    'ED': '5'
    'Other': '9'
    'default': '9'

  team:
    "Audies": "1"
    "PTer": "11"
    "OurBits": "10"
    "HDS": "9"
    "FRDS": "8"
    "CMCT": "7"
    "beAst": "6"
    "WiKi": "5"
    "TTG": "4"
    "BTN/NTb": "3"
    "HHWEB": "22"
    "Ubits": "13"
    "rainweb": "23"
    "rain": "24"
    "PTP": "20"
    "TLF": "19"
    "Hares": "18"
    "QHstudIo": "17"
    "PTHome": "16"
    "HDHome": "15"
    "HHClub": "14"
    "Other": "21"
    "default": "21"

  tag:
    "禁转": 1
    "首发": 2
    "DIY": 4
    "国语": 5
    "中字": 6
    "HDR": 7
    "default": null
