site_name: "13City"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  source: "processing_sel[4]"
  category: "type"  # 类别字段映射到type参数
  tags[4][]: "tags[]"  # 标签字段映射到tags参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    source:
      source_key: "区域"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "电影/Movies": "category.movie"
      "连续剧/TV Series": "category.tv_series"
      "综艺/TV Shows": "category.tv_shows"
      "动漫/Animations": "category.animation"
      "演唱会、MV/Music Videos": "category.mv"
      "音乐/Music": "category.music"
      "电子书&有声读物/E-book": "category.ebook"
      "纪录片/Docmentaries": "category.documentaries"

    medium:
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVDR": "medium.dvdr"
      "HDTV": "medium.hdtv"
      "MiniBD": "medium.minibd"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "HD DVD": "medium.hddvd"
      "Blu-ray": "medium.bluray"
      "WEB-DL": "medium.webdl"
      "BluRay": "medium.bluray"
      "WEBRip": "medium.webrip"
      "Other": "medium.other"

    video_codec:
      "AVC/H.264/x264": "video.h264"
      "HEVC/H.265/x265": "video.h265"
      "MPEG-2": "video.mpeg2"
      "VC-1": "video.vc1"
      "VPB/VP9": "video.vp9"
      "Xvid": "video.xvid"
      "Other": "video.other"

    audio_codec:
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "DTS-HD/DTS": "audio.dts"
      "MP3": "audio.mp3"
      "OGG": "audio.ogg"
      "AAC": "audio.aac"
      "DDP/E-AC3": "audio.ddp"
      "TrueHD": "audio.truehd"
      "TrueHD Atmos": "audio.truehd_atmos"
      "LPCM": "audio.lpcm"
      "Other": "audio.other"

    resolution:
      "8K": "resolution.r4320p"
      "4K": "resolution.r2160p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "Other": "resolution.other"

    team:
      "13City": "team.city13"
      "PTerWEB": "team.pterweb"
      "WiKi": "team.wiki"
      "UBits": "team.ubits"
      "ADWeb": "team.adweb"
      "ZmWeb": "team.zmweb"
      "UBWEB": "team.ubweb"
      "SewageWeb": "team.sewageweb"
      "Other": "team.other"
      "rainweb": "team.rainweb"
      "QHstudIo": "team.qhstudio"
      "MTeam": "team.mteam"
      "FRDS": "team.frds"
      "CHDWEB": "team.chdweb"
      "HHWEB": "team.hhweb"
      "52pt": "team.pt52"
      "AilMWeb": "team.ailmweb"

    source:
      "中国（含港澳台）": "source.china"
      "日本": "source.japan"
      "泰国": "source.thailand"
      "印度": "source.india"
      "韩国": "source.korea"
      "欧美": "source.western"
      "Other（其他）": "source.other"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.animation": "405"
    "category.mv": "406"
    "category.music": "408"
    "category.ebook": "409"
    "category.documentaries": "413"
    "category.other": "401"
    "default": "401"

  medium:
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvdr": "6"
    "medium.hdtv": "5"
    "medium.minibd": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.hddvd": "2"
    "medium.bluray": "1"
    "medium.webdl": "10"
    "medium.webrip": "12"
    "medium.other": "13"
    "default": "13"

  video_codec:
    "video.h264": "1"
    "video.h265": "2"
    "video.vc1": "4"
    "video.mpeg2": "3"
    "video.av1": "6"
    "video.vp9": "5"
    "video.xvid": "6"
    "video.other": "7"
    "default": "7"

  audio_codec:
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.dts": "3"
    "audio.mp3": "4"
    "audio.ogg": "5"
    "audio.aac": "6"
    "audio.other": "11"
    "audio.ac3": "7"
    "audio.truehd_atmos": "9"
    "audio.ddp": "7"
    "audio.lpcm": "10"
    "audio.truehd": "8"
    "audio.dtsx": "3"
    "audio.dts_hd_ma": "3"
    "audio.m4a": "11"
    "audio.wav": "11"
    "default": "11"

  resolution:
    "resolution.r4320p": "1"
    "resolution.r2160p": "2"
    "resolution.r1080p": "3"
    "resolution.r1080i": "4"
    "resolution.other": "5"
    "default": "5"

  source:
    "source.china": "1"
    "source.japan": "2"
    "source.thailand": "3"
    "source.india": "4"
    "source.korea": "5"
    "source.western": "6"
    "source.other": "7"
    "default": "7"

  team:
    "team.city13": "1"
    "team.ailmweb": "2"
    "team.pt52": "3"
    "team.hhweb": "4"
    "team.chdweb": "5"
    "team.frds": "6"
    "team.mteam": "7"
    "team.qhstudio": "8"
    "team.pterweb": "9"
    "team.rainweb": "10"
    "team.sewageweb": "12"
    "team.ubweb": "13"
    "team.zmweb": "14"
    "team.adweb": "15"
    "team.ubits": "16"
    "team.wiki": "17"
    "team.other": "11"
    "default": "11"

  tag:
    "tag.完结": 9
    "tag.分集": 8
    "tag.粤语": 13
    "tag.多语": 10
    "tag.国语": 5
    "tag.中字": 6
    "tag.中英双字": 14
    "tag.4K": 12
    "tag.1080p": 11
    "tag.HDR": 7
    "tag.DIY": 4
    "tag.红叶转载": 19
    "tag.有声图书": 15
    "default": null
