# CarPT站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "CarPT"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  source: "source_sel[4]"
  team: "team_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "电影/Movies": "category.movie"
      "连续剧/TV-Series": "category.tv_series"
      "动漫/Animation": "category.animation"
      "纪录片/Documentary": "category.documentaries"
      "综艺/TV-Show": "category.tv_shows"
      "音乐/Music": "category.music"
      "其他/Other": "category.other"

    medium:
      "Encode": "medium.encode"
      "WEB": "medium.webdl"
      "HDTV": "medium.hdtv"
      "DVDRip": "medium.dvdr"
      "CD": "medium.cd"
      "Other": "medium.other"
      "Blu-ray": "medium.bluray"
      "Blu-rayUHD": "medium.uhd_bluray"
      "Remux": "medium.remux"

    video_codec:
      "H.264/AVC/x264": "video.h264"
      "H.265/HEVC/x265": "video.h265"
      "MPEG-2": "video.mpeg2"
      "VC-1": "video.vc1"
      "Xvid": "video.xvid"
      "Other": "video.other"

    audio_codec:
      "TrueHD": "audio.truehd"
      "DTS-HD/DTS": "audio.dts"
      "AC3": "audio.ac3"
      "LPCM": "audio.lpcm"
      "FLAC": "audio.flac"
      "mp3": "audio.mp3"
      "AAC": "audio.aac"
      "APE": "audio.ape"
      "wav": "audio.wav"
      "Other": "audio.other"

    resolution:
      "4K_UHD": "resolution.r4k"
      "1080p/i": "resolution.r1080p"
      "720p/i": "resolution.r720p"
      "SD": "resolution.sd"
      "Other": "resolution.other"

    team:
      "CarPT": "team.carpt"
      "WiKi": "team.wiki"
      "CMCT": "team.cmct"
      "M-team": "team.mteam"
      "Other": "team.other"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.animation": "403"
    "category.documentaries": "404"
    "category.tv_shows": "405"
    "category.music": "406"
    "category.other": "407"
    "default": "407"

  medium:
    "medium.bluray": "7"
    "medium.uhd_bluray": "8"
    "medium.remux": "9"
    "medium.encode": "1"
    "medium.webdl": "2"
    "medium.hdtv": "3"
    "medium.dvdr": "4"
    "medium.cd": "5"
    "medium.other": "6"
    "default": "6"

  video_codec:
    "video.h264": "1"
    "video.h265": "2"
    "video.mpeg2": "3"
    "video.vc1": "4"
    "video.xvid": "5"
    "video.other": "6"
    "default": "6"

  audio_codec:
    "audio.truehd": "1"
    "audio.dts": "2"
    "audio.ac3": "3"
    "audio.lpcm": "4"
    "audio.flac": "5"
    "audio.mp3": "6"
    "audio.aac": "7"
    "audio.ape": "8"
    "audio.wav": "10"
    "audio.other": "9"
    "default": "9"

  resolution:
    "resolution.r4k": "1"
    "resolution.r1080p": "2"
    "resolution.r720p": "3"
    "resolution.sd": "4"
    "resolution.other": "5"
    "default": "5"

  team:
    "team.carpt": "1"
    "team.wiki": "2"
    "team.cmct": "3"
    "team.mteam": "4"
    "team.other": "5"
    "default": "5"

  tag:
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "default": null
