# Haidan站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "Haidan"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  category: "type"
  medium: "medium_sel"
  video_codec: "codec_sel"
  audio_codec: "audiocodec_sel"
  resolution: "standard_sel"
  team_suffix: "team_suffix"
  tag_list[]: "tag_list[]"

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team_suffix:
      source_key: "制作组后缀"

  # 标准化键映射规则（从原始文本到标准化键）
  # 将站点下拉菜单的文本映射到全局标准化键
  standard_keys:
    type:
      "Documentaries(纪录片)": "category.documentaries"
      "Movies(电影)": "category.movie"
      "Animations(动画片)": "category.animation"
      "TV Series(电视剧)": "category.tv_series"
      "TV Shows(综艺)": "category.tv_shows"
      "Music Videos(MV)": "category.music_video"
      "Sports(体育)": "category.sports"
      "Misc(其他)": "category.other"
      "HQ Audio(音乐)": "category.music"

    medium:
      "UHD Blu-ray": "medium.uhd_bluray"
      "Blu-ray": "medium.bluray"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "HDTV": "medium.hdtv"
      "WEB-DL": "medium.webdl"
      "DVD": "medium.dvd"
      "CD": "medium.cd"

    video_codec:
      "H.264/AVC/X264": "video.h264"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "Other": "video.other"
      "H.265/HEVC/X265": "video.h265"
      "MPEG-4/XviD/DivX": "video.mpeg4"

    audio_codec:
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "DTS": "audio.dts"
      "MP3": "audio.mp3"
      "AAC": "audio.aac"
      "Other": "audio.other"
      "AC3": "audio.ac3"
      "LPCM": "audio.lpcm"
      "DTS-HDMA": "audio.dts_hd_ma"
      "True-HD": "audio.truehd"

    resolution:
      "2160p/4K": "resolution.r2160p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "540P": "resolution.r540p"

    tag:
      "中字": "tag.中字"
      "DIY": "tag.DIY"
      "国语": "tag.国语"
      "原盘": "tag.原盘"
      "粤语": "tag.粤语"
      "外语": "tag.外语"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.documentaries": "404"
    "category.movie": "401"
    "category.animation": "405"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.music_video": "406"
    "category.sports": "407"
    "category.other": "409"
    "category.music": "408"
    "default": "401"

  medium:
    "medium.uhd_bluray": "9"
    "medium.bluray": "1"
    "medium.remux": "3"
    "medium.encode": "7"
    "medium.hdtv": "5"
    "medium.webdl": "11"
    "medium.dvd": "6"
    "medium.cd": "8"
    "default": "7"

  video_codec:
    "video.h264": "1"
    "video.vc1": "2"
    "video.mpeg2": "4"
    "video.other": "5"
    "video.h265": "11"
    "video.mpeg4": "13"
    "default": "5"

  audio_codec:
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.dts": "3"
    "audio.mp3": "4"
    "audio.aac": "6"
    "audio.other": "7"
    "audio.ac3": "10"
    "audio.lpcm": "11"
    "audio.dts_hd_ma": "12"
    "audio.truehd": "13"
    "default": "7"

  resolution:
    "resolution.r2160p": "1"
    "resolution.r1080p": "2"
    "resolution.r1080i": "3"
    "resolution.r720p": "4"
    "resolution.r540p": "5"
    "default": "4"

  tag:
    "tag.中字": 3
    "tag.DIY": 4
    "tag.国语": 5
    "tag.原盘": 7
    "tag.粤语": 10
    "tag.外语": 11
    "default": null
