# Luckpt站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "Luckpt"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    source:
      source_key: "产地"


  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "电影": "category.movie"
      "电视剧": "category.tv_series"
      "动画": "category.animation"
      "MV": "category.music_video"
      "音乐": "category.music"
      "其他": "category.other"
      "综艺": "category.tv_shows"
      "纪录片": "category.documentaries"
      "体育": "category.sports"
      "短剧": "category.playlet"

    medium:
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVD": "medium.dvd"
      "HDTV": "medium.hdtv"
      "MiniBD": "medium.minibd"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "Blu-ray": "medium.bluray"
      "UHD Blu-ray": "medium.uhd_bluray"
      "WEB-DL": "medium.webdl"
      "Other": "medium.other"

    video_codec:
      "H.264/AVC": "video.h264"
      "AV1": "video.av1"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "Other": "video.other"
      "H.265/HEVC": "video.h265"
      "MPEG-4/XviD": "video.xvid"

    audio_codec:
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "DTS": "audio.dts"
      "MP3": "audio.mp3"
      "OGG": "audio.ogg"
      "AAC": "audio.aac"
      "Other": "audio.other"
      "DD/AC3": "audio.ac3"
      "TrueHD Atmos": "audio.truehd_atmos"
      "DDP/E-AC3": "audio.ddp"
      "LPCM": "audio.lpcm"
      "TrueHD": "audio.truehd"
      "DTS:X": "audio.dtsx"
      "DTS-HD MA": "audio.dts_hd_ma"
      "M4A": "audio.m4a"
      "WAV": "audio.wav"

    resolution:
      "1080p/1080i": "resolution.r1080p"
      "720p/720i": "resolution.r720p"
      "480p/480i": "resolution.r480p"
      "2K/1440p/1440i": "resolution.r1440p"
      "4K/2160p/2160i": "resolution.r2160p"
      "8K/4320p/4320i": "resolution.r4320p"
      "Other": "resolution.other"

    team:
      "Other": "team.other"
      "LUCKWEB": "team.luckweb"
      "LUCKMUSIC": "team.luckmusic"
      "FRDS": "team.frds"
      "StarfallWeb": "team.starfallweb"

    tag:
      "禁转": "tag.禁转"
      "首发": "tag.首发"
      "DIY": "tag.DIY"
      "国语": "tag.国语"
      "中字": "tag.中字"
      "英语": "tag.英语"
      "菁彩HDR": "tag.菁彩HDR"
      "Dolby Vision": "tag.Dolby_Vision"
      "HDR10": "tag.hdr10"
      "HDR10+": "tag.hdr10plus"
      "合集": "tag.合集"
      "特效": "tag.特效"
      "粤语": "tag.粤语"
      "大包": "tag.大包"
      "完结": "tag.完结"
      "连载": "tag.连载"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.animation": "405"
    "category.music_video": "406"
    "category.music": "408"
    "category.other": "409"
    "category.tv_shows": "410"
    "category.documentaries": "411"
    "category.sports": "412"
    "category.playlet": "413"
    "default": "409"

  medium:
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvd": "6"
    "medium.hdtv": "5"
    "medium.minibd": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.bluray": "1"
    "medium.uhd_bluray": "10"
    "medium.webdl": "11"
    "medium.other": "13"
    "default": "13"

  video_codec:
    "video.h264": "1"
    "video.av1": "2"
    "video.vc1": "3"
    "video.mpeg2": "4"
    "video.other": "5"
    "video.h265": "6"
    "video.xvid": "12"
    "default": "5"

  audio_codec:
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.dts": "3"
    "audio.mp3": "4"
    "audio.ogg": "5"
    "audio.aac": "6"
    "audio.other": "7"
    "audio.ac3": "8"
    "audio.truehd_atmos": "11"
    "audio.ddp": "12"
    "audio.lpcm": "13"
    "audio.truehd": "14"
    "audio.dtsx": "15"
    "audio.dts_hd_ma": "16"
    "audio.m4a": "17"
    "audio.wav": "18"
    "default": "7"

  resolution:
    "resolution.r1080p": "1"
    "resolution.r720p": "3"
    "resolution.r480p": "4"
    "resolution.r1440p": "5"
    "resolution.r2160p": "6"
    "resolution.r4320p": "7"
    "resolution.other": "8"
    "default": "8"

  team:
    "team.other": "5"
    "team.luckweb": "7"
    "team.luckmusic": "8"
    "team.frds": "9"
    "team.starfallweb": "10"
    "default": "5"

  tag:
    "tag.禁转": 1
    "tag.首发": 2
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.英语": 22
    "tag.菁彩HDR": 21
    "tag.Dolby_Vision": 20
    "tag.hdr10": 19
    "tag.hdr10plus": 18
    "tag.合集": 17
    "tag.特效": 16
    "tag.粤语": 14
    "tag.大包": 11
    "tag.完结": 10
    "tag.连载": 9
    "default": null
