# March站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "March"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"


  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "Movies": "category.movie"
      "TV Series": "category.tv_series"
      "TV Shows": "category.tv_shows"
      "Documentaries": "category.documentaries"
      "Cartoon": "category.animation"
      "MTV": "category.music_video"
      "Sports": "category.sports"
      "Music": "category.music"
      "Misc": "category.other"

    medium:
      "WEB-DL": "medium.webdl"
      "DVD": "medium.dvd"
      "HDTV": "medium.hdtv"
      "Other": "medium.other"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "DVDR": "medium.dvdr"
      "Blu-Ray": "medium.bluray"

    video_codec:
      "H.264": "video.h264"
      "HEVC": "video.h265"
      "H.265": "video.h265"
      "MPEG-2": "video.mpeg2"
      "MPEG-4": "video.mpeg4"
      "X.264": "video.x264"
      "X.265": "video.x265"
      "XVID": "video.xvid"
      "AV1": "video.av1"
      "Other": "video.other"

    resolution:
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "576P": "resolution.r576p"
      "2160P": "resolution.r2160p"
      "480P": "resolution.r480p"
      "4320P": "resolution.r4320p"

    team:
      "3MWEB": "team.3mweb"
      "CHD": "team.chd"
      "TTG": "team.ttg"
      "CMCT": "team.cmct"
      "HDSKY": "team.hdsky"
      "OurBits": "team.ourbits"
      "M-Team": "team.mteam"
      "WIKI": "team.wiki"
      "Beast": "team.beast"
      "HHWEB": "team.hhweb"
      "Other": "team.other"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.music_video": "406"
    "category.sports": "407"
    "category.music": "408"
    "category.other": "409"
    "default": "401"

  medium:
    "medium.webdl": "13"
    "medium.dvd": "8"
    "medium.hdtv": "5"
    "medium.other": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.dvdr": "2"
    "medium.bluray": "1"
    "default": "4"

  video_codec:
    "video.h264": "1"
    "video.h265": "2"
    "video.mpeg2": "4"
    "video.mpeg4": "5"
    "video.x264": "6"
    "video.x265": "7"
    "video.xvid": "9"
    "video.av1": "10"
    "video.other": "11"
    "default": "11"

  resolution:
    "resolution.r1080p": "1"
    "resolution.r1080i": "2"
    "resolution.r720p": "3"
    "resolution.r576p": "4"
    "resolution.r2160p": "6"
    "resolution.r480p": "7"
    "resolution.r4320p": "8"
    "default": "7"

  team:
    "team.3mweb": "1"
    "team.chd": "2"
    "team.ttg": "3"
    "team.cmct": "4"
    "team.hdsky": "5"
    "team.ourbits": "6"
    "team.mteam": "7"
    "team.wiki": "8"
    "team.beast": "9"
    "team.hhweb": "10"
    "team.other": "11"
    "default": "11"

  tag:
    "tag.禁转": 1
    "tag.首发": 2
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "default": null
