# Novahd站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "Novahd"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "电影/Movies": "category.movie"
      "电视剧/TV Series": "category.tv_series"
      "综艺/TV Shows": "category.tv_shows"
      "记录片/Documentaries": "category.documentaries"
      "动漫、动画/Animations": "category.animation"
      "演唱会/MV": "category.mv"
      "体育/Sports": "category.sports"
      "音乐/Music": "category.music"
      "其他/Othes": "category.other"

    medium:
      "DVD": "medium.dvd"
      "WEB-DL": "medium.webdl"
      "UHD Blu-ray": "medium.uhd_bluray"
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVDR": "medium.dvdr"
      "HDTV": "medium.hdtv"
      "MiniBD": "medium.minibd"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "HD DVD": "medium.hddvd"
      "Blu-ray": "medium.bluray"

    video_codec:
      "AVC/H.264/x264": "video.h264"
      "VC-1": "video.vc1"
      "Xvid": "video.xvid"
      "MPEG-2": "video.mpeg2"
      "Other": "video.other"
      "HEVC/H.265/x265": "video.h265"

    audio_codec:
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "DTS": "audio.dts"
      "MP3": "audio.mp3"
      "OGG": "audio.ogg"
      "AAC": "audio.aac"
      "ALAC": "audio.alac"
      "TrueHD Atmos": "audio.truehd_atmos"
      "DDP/E-AC3": "audio.ddp"
      "DD/AC3": "audio.ac3"
      "LPCM": "audio.lpcm"
      "TrueHD": "audio.truehd"
      "DTS-HD MA": "audio.dts_hd_ma"
      "DTS:X": "audio.dtsx"
      "Other": "audio.other"

    resolution:
      "1080p/i": "resolution.r1080p"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "4K/2160p": "resolution.r2160p"
      "8K/4320p": "resolution.r4320p"

    team:
      "HDSky": "team.hdsky"
      "CHD": "team.chd"
      "MySiLU": "team.mysilu"
      "WiKi": "team.wiki"
      "Other": "team.other"
      "FRDS": "team.frds"
      "beAst": "team.beast"
      "CMCT": "team.cmct"
      "TLF": "team.tlf"
      "M-Team": "team.mteam"
      "BeiTai": "team.beitai"
      "AGSV": "team.agsv"
      "HDHome": "team.hdhome"
      "TTG": "team.ttg"
      "NHDWeb": "team.nhdweb"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.mv": "406"
    "category.sports": "407"
    "category.music": "409"
    "category.other": "410"
    "default": "410"

  medium:
    "medium.dvd": "12"
    "medium.webdl": "11"
    "medium.uhd_bluray": "10"
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvdr": "6"
    "medium.hdtv": "5"
    "medium.minibd": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.hddvd": "2"
    "medium.bluray": "1"
    "default": "16"

  video_codec:
    "video.h264": "1"
    "video.vc1": "2"
    "video.xvid": "3"
    "video.mpeg2": "4"
    "video.other": "5"
    "video.h265": "6"
    "default": "5"

  audio_codec:
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.dts": "3"
    "audio.mp3": "4"
    "audio.ogg": "5"
    "audio.aac": "6"
    "audio.alac": "7"
    "audio.truehd_atmos": "8"
    "audio.ddp": "9"
    "audio.ac3": "10"
    "audio.lpcm": "11"
    "audio.truehd": "12"
    "audio.dts_hd_ma": "13"
    "audio.dtsx": "14"
    "audio.other": "15"
    "default": "15"

  resolution:
    "resolution.r1080p": "1"
    "resolution.r1080i": "2"
    "resolution.r720p": "3"
    "resolution.sd": "4"
    "resolution.r2160p": "5"
    "resolution.r4320p": "6"
    "default": "6"

  team:
    "team.hdsky": "1"
    "team.chd": "2"
    "team.mysilu": "3"
    "team.wiki": "4"
    "team.other": "5"
    "team.frds": "6"
    "team.beast": "7"
    "team.cmct": "8"
    "team.tlf": "9"
    "team.mteam": "10"
    "team.beitai": "11"
    "team.agsv": "12"
    "team.hdhome": "13"
    "team.ttg": "14"
    "team.nhdweb": "15"
    "default": "5"

  tag:
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "tag.连载": 18
    "tag.番组": 17
    "tag.特效": 15
    "tag.杜比": 14
    "tag.大包": 13
    "tag.英字": 11
    "tag.完结": 10
    "tag.分集": 9
    "default": null
