# 0ff.cc站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "0ffCC"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  source: "source_sel[4]"
  resolution: "standard_sel[4]"
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  team: "team_sel[4]"
  processing: "processing_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    source:
      source_key: "地区"
    resolution:
      source_key: "分辨率"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    team:
      source_key: "制作组"
    processing:
      source_key: "内容分级"

  title_components:
    title:
      source_key: "主标题"
    season_episode:
      source_key: "季集"
    year:
      source_key: "年份"
    status:
      source_key: "剧集状态"
    edition:
      source_key: "发布版本"
    resolution:
      source_key: "分辨率"
    platform:
      source_key: "片源平台"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    video_format:
      source_key: "视频格式"
    hdr_format:
      source_key: "HDR格式"
    bit_depth:
      source_key: "色深"
    frame_rate:
      source_key: "帧率"
    audio_codec:
      source_key: "音频编码"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "Movies|电影": "category.movie"
      "TV Series|电视剧": "category.tv_series"
      "Documentaries|纪录片": "category.documentaries"
      "TV Shows|综艺": "category.tv_shows"
      "Animations|动漫": "category.animation"
      "Music Videos|音乐视频": "category.mv"
      "HD Music|无损音乐": "category.music"
      "Sports|体育": "category.sports"
      "Education|学习教育": "category.study"
      "book|书籍": "category.book"
      "Game|游戏": "category.game"
      "Resources|网络资源": "category.resources"
      "待定": "category.other"
      "Others|其他": "category.other"
      "Children's film|儿童电影": "category.children_movie"
      "Children's TV series​|儿童剧集": "category.children_tv_series"
      "Children's documentaries|儿童记录片": "category.children_documentaries"
      "picture books|儿童音乐": "category.children_music"
      "Audiobooks|有声读物": "category.audiobook"
      "picture books|书籍绘本": "category.picture_book"

    source:
      "内地 (China,CHN)": "source.china"
      "香港 (HKG,CHN)": "source.hongkong"
      "台湾 (TWN,CHN)": "source.taiwan"
      "韩国 (KOR)": "source.korea"
      "欧美 (Western)": "source.western"
      "日本 (JPN)": "source.japan"
      "印度 (IND)": "source.india"
      "泰国 (Th)": "source.thailand"
      "其它 (Other)": "source.other"

    resolution:
      "8K/4320P": "resolution.r4320p"
      "4K/2160P": "resolution.r2160p"
      "1080P": "resolution.r1080p"
      "1440P": "resolution.r1440p"
      "1080I": "resolution.r1080i"
      "720P": "resolution.r720p"
      "SD": "resolution.sd"
      "其它 (Other)": "resolution.other"

    medium:
      "UHD Blu-ray": "medium.uhd_bluray"
      "Blu-ray": "medium.bluray"
      "UHDTV": "medium.uhdtv"
      "IPTV": "medium.iptv"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "HDTV": "medium.hdtv"
      "DVDR": "medium.dvdr"
      "CD": "medium.cd"
      "MiniBD": "medium.minibd"
      "Track": "medium.track"
      "WEB-DL": "medium.webdl"
      "SACD": "medium.sacd"
      "HD DVD": "medium.hddvd"
      "3D Blu-ray": "medium.3d_bluray"
      "其它 (Other)": "medium.other"

    video_codec:
      "H.265/HEVC": "video.h265"
      "H.264/AVC": "video.h264"
      "X265": "video.x265"
      "X264": "video.x264"
      "HEVC": "video.h265"
      "VC-1": "video.vc1"
      "MPEG-4": "video.mpeg4"
      "MPEG-2": "video.mpeg2"
      "Xvid": "video.xvid"
      "MVC": "video.mvc"
      "ProRes": "video.prores"
      "VP8/9": "video.vp9"
      "AV1": "video.av1"
      "其它 (Other)": "video.other"

    audio_codec:
      "DTS-HDMA:X 7.1": "audio.dts_hdma_x71"
      "TrueHD Atmos": "audio.truehd_atmos"
      "FLAC": "audio.flac"
      "OPUS": "audio.opus"
      "LPCM": "audio.lpcm"
      "DTS-X": "audio.dtsx"
      "TrueHD": "audio.truehd"
      "AC3|DD": "audio.ac3"
      "DTS-HD|MA": "audio.dts_hd_ma"
      "DTS-HD|HR": "audio.dts_hd_hr"
      "DTS": "audio.dts"
      "PCM": "audio.pcm"
      "DSD": "audio.dsd"
      "APE": "audio.ape"
      "AAC": "audio.aac"
      "MP3": "audio.mp3"
      "WAV": "audio.wav"
      "OGG": "audio.ogg"
      "其它 (Other)": "audio.other"
      "DTS-HDMA": "audio.dts_hdma"
      "E-AC3 Atmos(DDP Atmos)": "audio.ddp_atmos"
      "E-AC3(DDP)": "audio.ddp"
      "AC3(DD)": "audio.ac3"

    team:
      "FFWEB": "team.ffweb"
      "其它 (Other)": "team.other"

    processing:
      "G/所有人": "processing.g"
      "PG/建议陪同": "processing.pg"
      "PG-13/13 岁+，建议陪同": "processing.pg13"
      "TV-Y/所有儿童": "processing.tv_y"
      "TV-Y7/7 岁+": "processing.tv_y7"
      "TV-G/所有人": "processing.tv_g"
      "TV-PG/建议陪同": "processing.tv_pg"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.documentaries": "403"
    "category.tv_shows": "404"
    "category.animation": "405"
    "category.mv": "406"
    "category.music": "407"
    "category.sports": "408"
    "category.study": "427"
    "category.book": "412"
    "category.game": "411"
    "category.resources": "410"
    "category.other": "428"
    "category.children_movie": "413"
    "category.children_tv_series": "414"
    "category.children_documentaries": "415"
    "category.children_music": "416"
    "category.audiobook": "417"
    "category.picture_book": "425"
    "default": "428"

  source:
    "source.china": "35"
    "source.hongkong": "36"
    "source.taiwan": "37"
    "source.korea": "39"
    "source.western": "38"
    "source.japan": "40"
    "source.india": "41"
    "source.thailand": "34"
    "source.other": "42"
    "default": "42"

  resolution:
    "resolution.r4320p": "1"
    "resolution.r2160p": "2"
    "resolution.r1080p": "3"
    "resolution.r1440p": "4"
    "resolution.r1080i": "5"
    "resolution.r720p": "6"
    "resolution.sd": "7"
    "resolution.other": "14"
    "default": "14"

  medium:
    "medium.uhd_bluray": "1"
    "medium.bluray": "2"
    "medium.uhdtv": "3"
    "medium.iptv": "4"
    "medium.remux": "5"
    "medium.encode": "6"
    "medium.hdtv": "7"
    "medium.dvdr": "8"
    "medium.cd": "9"
    "medium.minibd": "10"
    "medium.track": "11"
    "medium.webdl": "12"
    "medium.sacd": "13"
    "medium.hddvd": "14"
    "medium.3d_bluray": "15"
    "medium.other": "21"
    "default": "21"

  video_codec:
    "video.h265": "1"
    "video.h264": "2"
    "video.x265": "3"
    "video.x264": "4"
    "video.vc1": "6"
    "video.mpeg4": "7"
    "video.mpeg2": "8"
    "video.xvid": "9"
    "video.mvc": "10"
    "video.prores": "11"
    "video.vp9": "12"
    "video.av1": "13"
    "video.other": "14"
    "default": "14"

  audio_codec:
    "audio.dts_hdma_x71": "10"
    "audio.truehd_atmos": "1"
    "audio.flac": "9"
    "audio.opus": "8"
    "audio.lpcm": "7"
    "audio.dtsx": "6"
    "audio.truehd": "5"
    "audio.ac3": "4"
    "audio.dts_hd_ma": "2"
    "audio.dts_hd_hr": "3"
    "audio.dts": "14"
    "audio.pcm": "17"
    "audio.dsd": "16"
    "audio.ape": "15"
    "audio.aac": "13"
    "audio.mp3": "12"
    "audio.wav": "11"
    "audio.ogg": "21"
    "audio.other": "22"
    "audio.dts_hdma": "18"
    "audio.ddp_atmos": "23"
    "audio.ddp": "24"
    "default": "22"

  team:
    "team.ffweb": "15"
    "team.other": "14"
    "default": "14"

  processing:
    "processing.g": "18"
    "processing.pg": "19"
    "processing.pg13": "20"
    "processing.tv_y": "21"
    "processing.tv_y7": "22"
    "processing.tv_g": "23"
    "processing.tv_pg": "24"
    "default": "18"

  tag:
    "tag.连载": 12
    "tag.完结": 10
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "tag.短剧": 8
    "tag.3D": 11
    "default": null
