# Ptcafe站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "Ptcafe"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  source: "source_sel[4]"
  team: "team_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    source:
      source_key: "产地"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "电影": "category.movie"
      "剧集": "category.tv_series"
      "综艺": "category.tv_shows"
      "纪录": "category.documentaries"
      "动漫": "category.animation"
      "演唱": "category.music_video"
      "体育": "category.sports"
      "音乐": "category.music"
      "其他": "category.other"

    medium:
      "UHD Blu-ray 原盘": "medium.uhd_bluray"
      "UHD Blu-ray DIY": "medium.uhd_bluray_diy"
      "UHD Remux": "medium.uhd_remux"
      "Blu-ray 原盘": "medium.bluray"
      "Blu-ray DIY": "medium.bluray_diy"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "WEB-DL": "medium.webdl"
      "TV": "medium.hdtv"
      "DVD": "medium.dvd"
      "CD": "medium.cd"
      "Track": "medium.track"
      "Other": "medium.other"

    video_codec:
      "H.265/HEVC": "video.h265"
      "H.264/AVC": "video.h264"
      "X265": "video.x265"
      "X264": "video.x264"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "MPEG-4": "video.mpeg4"
      "X264": "video.x264"
      "XVID": "video.xvid"
      "VP9": "video.vp9"
      "DIVX": "video.divx"
      "Other": "video.other"

    audio_codec:
      "DTS-HDMA:X 7.1": "audio.dts_hdma_x71"
      "DTS-HDMA": "audio.dts_hdma"
      "DTS-HDHR": "audio.dts_hd_hr"
      "DTS-HD": "audio.dts_hd"
      "DTS-X": "audio.dtsx"
      "LPCM": "audio.lpcm"
      "AC3": "audio.ac3"
      "Atmos": "audio.atmos"
      "AAC": "audio.aac"
      "TrueHD": "audio.truehd"
      "DTS": "audio.dts"
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "MP3": "audio.mp3"
      "WAV": "audio.wav"
      "OPUS": "audio.opus"
      "OGG": "audio.ogg"
      "Other": "audio.other"

    resolution:
      "4320P/8K/FUHD": "resolution.r4320p"
      "2160P/4K/UHD": "resolution.r2160p"
      "1080p/1080i/FHD": "resolution.r1080p"
      "720p/720i/HD": "resolution.r720p"
      "360p/360i/SD": "resolution.r360p"
      "Other": "resolution.other"

    source:
      "大陆": "source.china"
      "港台": "source.hongkong"
      "欧美": "source.western"
      "日本": "source.japan"
      "韩国": "source.korea"
      "印度": "source.india"
      "其他": "source.other"

    team:
      "ADE": "team.ade"
      "ADWeb": "team.adweb"
      "Audies": "team.audies"
      "beAst": "team.beast"
      "BeiTai": "team.beitai"
      "BeyondHD": "team.beyondhd"
      "BtsTV": "team.btstv"
      "CafeTV": "team.cafetv"
      "CafeWEB": "team.cafeweb"
      "CHDBits": "team.chdbits"
      "CHDWEB": "team.chdweb"
      "CMCT": "team.cmct"
      "DJWEB": "team.djweb"
      "FRDS": "team.frds"
      "HDCTV": "team.hdctv"
      "HDH": "team.hdh"
      "HDHome": "team.hdhome"
      "HDSky": "team.hdsky"
      "HDSWEB": "team.hdsweb"
      "HHWEB": "team.hhweb"
      "MTeam": "team.mteam"
      "MWeb": "team.mweb"
      "OurBits": "team.ourbits"
      "OurTV": "team.ourtv"
      "PTCafe": "team.ptcafe"
      "PTerWEB": "team.pterweb"
      "QHstudIo": "team.qhstudio"
      "TTG": "team.ttg"
      "WiKi": "team.wiki"
      "Other": "team.other"

    tag:
      "官方": "tag.官方"
      "首发": "tag.首发"
      "完结": "tag.完结"
      "原创": "tag.原创"
      "禁转": "tag.禁转"
      "国语": "tag.国语"
      "粤语": "tag.粤语"
      "中字": "tag.中字"
      "备胎": "tag.备胎"
      "杜比视界": "tag.杜比视界"
      "HDR": "tag.HDR"
      "DIY": "tag.DIY"
      "应求": "tag.应求"
      "高码高帧": "tag.高码高帧"
      "月月": "tag.月月"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.music_video": "406"
    "category.sports": "407"
    "category.music": "408"
    "category.other": "409"
    "default": "409"

  medium:
    "medium.uhd_bluray": "1"
    "medium.uhd_bluray_diy": "2"
    "medium.uhd_remux": "3"
    "medium.bluray": "4"
    "medium.bluray_diy": "5"
    "medium.remux": "6"
    "medium.encode": "7"
    "medium.webdl": "8"
    "medium.hdtv": "9"
    "medium.dvd": "10"
    "medium.cd": "11"
    "medium.track": "12"
    "medium.other": "13"
    "default": "13"

  video_codec:
    "video.h265": "1"
    "video.h264": "2"
    "video.x265": "3"
    "video.x264": "4"
    "video.vc1": "5"
    "video.mpeg2": "6"
    "video.mpeg4": "7"
    "video.x264": "4"
    "video.xvid": "8"
    "video.vp9": "9"
    "video.divx": "10"
    "video.other": "11"
    "default": "11"

  audio_codec:
    "audio.dts_hdma_x71": "1"
    "audio.dts_hdma": "2"
    "audio.dts_hd_hr": "3"
    "audio.dts_hd": "4"
    "audio.dtsx": "5"
    "audio.lpcm": "6"
    "audio.ac3": "7"
    "audio.atmos": "8"
    "audio.aac": "9"
    "audio.truehd": "10"
    "audio.dts": "11"
    "audio.flac": "12"
    "audio.ape": "13"
    "audio.mp3": "14"
    "audio.wav": "15"
    "audio.opus": "16"
    "audio.ogg": "17"
    "audio.other": "18"
    "default": "18"

  resolution:
    "resolution.r4320p": "1"
    "resolution.r2160p": "2"
    "resolution.r1080p": "3"
    "resolution.r720p": "4"
    "resolution.r360p": "5"
    "resolution.other": "6"
    "default": "6"

  source:
    "source.china": "1"
    "source.hongkong": "2"
    "source.western": "3"
    "source.japan": "4"
    "source.korea": "5"
    "source.india": "6"
    "source.other": "7"
    "default": "7"

  team:
    "team.ade": "1"
    "team.adweb": "2"
    "team.audies": "3"
    "team.beast": "4"
    "team.beitai": "5"
    "team.beyondhd": "6"
    "team.btstv": "7"
    "team.cafetv": "8"
    "team.cafeweb": "9"
    "team.chdbits": "10"
    "team.chdweb": "11"
    "team.cmct": "12"
    "team.djweb": "13"
    "team.frds": "14"
    "team.hdctv": "15"
    "team.hdh": "16"
    "team.hdhome": "17"
    "team.hdsky": "18"
    "team.hdsweb": "19"
    "team.hhweb": "20"
    "team.mteam": "21"
    "team.mweb": "22"
    "team.ourbits": "23"
    "team.ourtv": "24"
    "team.ptcafe": "25"
    "team.pterweb": "26"
    "team.qhstudio": "27"
    "team.ttg": "28"
    "team.wiki": "29"
    "team.other": "30"
    "default": "30"

  tag:
    "tag.官方": 1
    "tag.首发": 2
    "tag.完结": 3
    "tag.原创": 4
    "tag.禁转": 5
    "tag.国语": 7
    "tag.粤语": 8
    "tag.中字": 9
    "tag.备胎": 10
    "tag.杜比视界": 11
    "tag.HDR": 12
    "tag.DIY": 13
    "tag.应求": 14
    "tag.高码高帧": 15
    "tag.月月": 16
    "default": null
