# PTZone站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "PTZone"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  category: "type"
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  tags[]: "tags[4][]"

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  # 将站点下拉菜单的文本映射到全局标准化键
  standard_keys:
    type:
      "Movies(电影)": "category.movie"
      "TV Series(电视剧)": "category.tv_series"
      "TV Shows(综艺)": "category.tv_shows"
      "Documentaries(纪录片)": "category.documentaries"
      "Animations(动漫)": "category.animation"
      "Music(音乐)": "category.music"
      "Sports(体育)": "category.sports"
      "Software(软件)": "category.software"
      "Games(游戏)": "category.game"
      "Others(其它）": "category.other"

    medium:
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVDR": "medium.dvdr"
      "HDTV": "medium.hdtv"
      "WEB-DL": "medium.webdl"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "HD DVD": "medium.hddvd"
      "Blu-ray": "medium.bluray"
      "UHD": "medium.uhd_bluray"

    video_codec:
      "H.264": "video.h264"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "MPEG-4": "video.mpeg4"
      "Other": "video.other"
      "H.265": "video.h265"

    audio_codec:
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "DTS": "audio.dts"
      "MP3": "audio.mp3"
      "OGG": "audio.ogg"
      "AAC": "audio.aac"
      "Other": "audio.other"
      "AC3": "audio.ac3"
      "DTS-HD MA": "audio.dts_hd_ma"
      "DD/AC3": "audio.ac3"
      "DDP/EAC3": "audio.ddp"
      "DTS-HD": "audio.dts_hd"
      "TrueHD": "audio.truehd"
      "WAV": "audio.wav"

    resolution:
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "8K": "resolution.r4320p"
      "4K": "resolution.r2160p"

    team:
      "PTZWeb": "team.ptzweb"
      "HDS": "team.hds"
      "CHD": "team.chd"
      "MySiLU": "team.mysilu"
      "WiKi": "team.wiki"
      "Other": "team.other"

    tag:
      "完结": "tag.完结"
      "分集": "tag.分集"
      "禁转": "tag.禁转"
      "首发": "tag.首发"
      "DIY": "tag.DIY"
      "国语": "tag.国语"
      "中字": "tag.中字"
      "HDR": "tag.HDR"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.music": "406"
    "category.sports": "407"
    "category.software": "410"
    "category.game": "411"
    "category.other": "409"
    "default": "401"

  medium:
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvdr": "6"
    "medium.hdtv": "5"
    "medium.webdl": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.hddvd": "2"
    "medium.bluray": "1"
    "medium.uhd_bluray": "10"
    "default": "7"

  video_codec:
    "video.h264": "1"
    "video.vc1": "2"
    "video.mpeg2": "3"
    "video.mpeg4": "4"
    "video.other": "5"
    "video.h265": "6"
    "default": "5"

  audio_codec:
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.dts": "3"
    "audio.mp3": "4"
    "audio.ogg": "5"
    "audio.aac": "6"
    "audio.other": "7"
    "audio.ac3": "8"
    "audio.dts_hd_ma": "10"
    "audio.ddp": "12"
    "audio.dts_hd": "13"
    "audio.truehd": "14"
    "audio.wav": "15"
    "default": "7"

  resolution:
    "resolution.r1080p": "1"
    "resolution.r1080i": "2"
    "resolution.r720p": "3"
    "resolution.sd": "4"
    "resolution.r4320p": "5"
    "resolution.r2160p": "6"
    "default": "4"

  team:
    "team.ptzweb": "6"
    "team.hds": "1"
    "team.chd": "2"
    "team.mysilu": "3"
    "team.wiki": "4"
    "team.other": "5"
    "default": "5"

  tag:
    "tag.完结": 9
    "tag.分集": 8
    "tag.禁转": 1
    "tag.首发": 2
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "default": null
