site_name: "SSD"

form_fields:
  category: "type"
  source: "source_sel"
  medium: "medium_sel"
  resolution: "standard_sel"
  video_codec: "codec_sel"
  audio_codec: "audiocodec_sel"

source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    source:
      source_key: "产地"

  standard_keys:
    type:
      "Movies(电影)": "category.movie"
      "TV Series(剧集)": "category.tv_series"
      "Docs(纪录)": "category.documentaries"
      "TV Shows(综艺)": "category.tv_shows"
      "Sports(体育)": "category.sports"
      "MV(音乐视频)": "category.mv"
      "Music(音乐)": "category.music"
      "Audio(有声)": "category.audiobook"
      "Other(其他类型)": "category.other"

    source:
      "Mainland(大陆)": "source.china"
      "Hongkong(香港)": "source.hongkong"
      "Taiwan(台湾)": "source.taiwan"
      "West(欧美)": "source.western"
      "Japan(日本)": "source.japan"
      "Korea(韩国)": "source.korea"
      "India(印度)": "source.india"
      "Russia(俄国)": "source.russia"
      "Thailand(泰国)": "source.thailand"
      "Other(其他地区)": "source.other"

    medium:
      "Blu-ray": "medium.bluray"
      "Remux": "medium.remux"
      "MiniBD": "medium.minibd"
      "BDRip": "medium.bdrip"
      "WEB-DL": "medium.webdl"
      "WEBRip": "medium.webrip"
      "HDTV": "medium.hdtv"
      "TVRip": "medium.tvrip"
      "DVD": "medium.dvd"
      "DVDRip": "medium.dvdrip"
      "CD": "medium.cd"
      "Other": "medium.other"

    video_codec:
      "H.265/HEVC": "video.h265"
      "H.264/AVC": "video.h264"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "AV1": "video.av1"
      "Other": "video.other"

    audio_codec:
      "DTS-HD": "audio.dts_hd_ma"
      "TrueHD": "audio.truehd"
      "LPCM": "audio.lpcm"
      "DTS": "audio.dts"
      "E-AC-3": "audio.ddp"
      "AC-3": "audio.ac3"
      "AAC": "audio.aac"
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "WAV": "audio.wav"
      "MP3": "audio.mp3"
      "OPUS": "audio.opus"
      "Other": "audio.other"

    resolution:
      "2160p": "resolution.r2160p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "Other": "resolution.other"

    team:
      "CMCT": "team.cmct"
      "WiKi": "team.wiki"
      "MTeam": "team.mteam"
      "DOUHD": "team.douhd"
      "HONE": "team.hone"
      "BYNDR": "team.byndr"
      "HHWEB": "team.hhweb"

    tag:
      "动画": "tag.动画"
      "禁转": "tag.禁转"
      "合集": "tag.合集"
      "原生": "tag.原生"
      "国配": "tag.国语"
      "中字": "tag.中字"
      "特效": "tag.特效"
      "自译": "tag.自译"
      "DoVi": "tag.Dolby_Vision"
      "HDR10": "tag.hdr10"
      "HDR10+": "tag.hdr10plus"
      "菁彩HDR": "tag.菁彩HDR"
      "HLG": "tag.hlg"
      "CC": "tag.cc"
      "3D": "tag.3d"
      "国语": "tag.国语"
      "粤语": "tag.粤语"
      "杜比": "tag.杜比"
      "特效字幕": "tag.特效"
      "英字": "tag.英字"
      "4K": "tag.4K"
      "Blu-ray": "tag.Blu-ray"
      "LIVE现场": "tag.LIVE现场"
      "default": null
