# Xingyunge站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "Xingyunge"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  category: "type"  # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "其他": "category.other"
      "音频": "category.music"
      "MV": "category.music_video"
      "体育": "category.sports"
      "短剧": "category.playlet"
      "纪录片": "category.documentaries"
      "动漫": "category.animation"
      "综艺": "category.tv_shows"
      "电视剧": "category.tv_series"
      "电影": "category.movie"

    medium:
      "Other": "medium.other"
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVD": "medium.dvd"
      "HDTV": "medium.hdtv"
      "WEB-DL": "medium.webdl"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "Blu-ray": "medium.bluray"
      "UHD Blu-ray": "medium.uhd_bluray"

    video_codec:
      "H.264/AVC": "video.h264"
      "H.265/HEVC": "video.h265"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "AV1": "video.av1"
      "Other": "video.other"

    audio_codec:
      "ALAC": "audio.alac"
      "AAC": "audio.aac"
      "APE": "audio.ape"
      "TrueHD Atmos": "audio.truehd_atmos"
      "DDP/E-AC3": "audio.ddp"
      "DD/AC3": "audio.ac3"
      "LPCM": "audio.lpcm"
      "TrueHD": "audio.truehd"
      "DTS:X": "audio.dtsx"
      "DTS-HD MA": "audio.dts_hd_ma"
      "DTS": "audio.dts"
      "M4A": "audio.m4a"
      "WAV": "audio.wav"
      "MP3": "audio.mp3"
      "FLAC": "audio.flac"
      "Other": "audio.other"
      "OPUS": "audio.opus"
      "AV3V": "audio.av3v"

    resolution:
      "480p/480i": "resolution.r480p"
      "720p/720i": "resolution.r720p"
      "1080p/1080i": "resolution.r1080p"
      "4K/2160p/2160i": "resolution.r2160p"
      "8k/4320p/4320i": "resolution.r4320p"
      "Other": "resolution.other"

    team:
      "WiKi": "team.wiki"
      "MySiLU": "team.mysilu"
      "HDS": "team.hds"
      "CHD": "team.chd"
      "Other": "team.other"
      "rainweb": "team.rainweb"
      "rain": "team.rain"
      "StarfallWeb": "team.starfallweb"
      "AGSVWEB": "team.agsvweb"
      "Starfall": "team.starfall"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.other": "409"
    "category.music": "408"
    "category.music_video": "406"
    "category.sports": "407"
    "category.playlet": "410"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.tv_shows": "403"
    "category.tv_series": "402"
    "category.movie": "401"
    "default": "409"

  medium:
    "medium.other": "10"
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvd": "6"
    "medium.hdtv": "5"
    "medium.webdl": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.bluray": "1"
    "medium.uhd_bluray": "2"
    "default": "10"

  video_codec:
    "video.h264": "1"
    "video.h265": "2"
    "video.vc1": "3"
    "video.mpeg2": "4"
    "video.av1": "5"
    "video.other": "6"
    "default": "6"

  audio_codec:
    "audio.alac": "15"
    "audio.aac": "14"
    "audio.ape": "13"
    "audio.truehd_atmos": "12"
    "audio.ddp": "11"
    "audio.ac3": "10"
    "audio.lpcm": "9"
    "audio.truehd": "8"
    "audio.dtsx": "7"
    "audio.dts_hd_ma": "6"
    "audio.dts": "5"
    "audio.m4a": "4"
    "audio.wav": "3"
    "audio.mp3": "2"
    "audio.flac": "1"
    "audio.other": "16"
    "audio.opus": "17"
    "audio.av3v": "18"
    "default": "16"

  resolution:
    "resolution.r480p": "1"
    "resolution.r720p": "2"
    "resolution.r1080p": "3"
    "resolution.r2160p": "4"
    "resolution.r4320p": "5"
    "resolution.other": "6"
    "default": "6"

  team:
    "team.wiki": "4"
    "team.mysilu": "3"
    "team.hds": "1"
    "team.chd": "2"
    "team.other": "5"
    "team.rainweb": "7"
    "team.rain": "6"
    "team.starfallweb": "8"
    "team.agsvweb": "9"
    "team.starfall": "10"
    "default": "5"

  tag:
    "tag.国语": 5
    "tag.中字": 6
    "tag.补帧": 20
    "tag.超分": 19
    "tag.特效": 18
    "tag.大包": 17
    "tag.应求": 16
    "tag.英字": 15
    "tag.韩剧": 14
    "tag.美剧": 13
    "tag.粤语": 12
    "tag.特效字幕": 9
    "tag.杜比视界": 8
    "tag.DIY": 4
    "tag.HDR": 7
    "tag.原生": 24
    "tag.完结": 11
    "tag.分集": 10
    "default": null
