# 站点名称
site_name: "YHPP"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
# 根据HTML中的 <select name="..."> 或 <input name="..."> 确定
form_fields:
  category: "type"
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  source: "processing_sel[4]" # 该站点的地区字段名为 processing_sel
  team: "team_sel[4]"
  tags[4][]: "tags[]"

# 源解析器 - 定义如何从原始数据中解析出标准化参数
source_parsers:
  # 源参数定义
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    source:
      source_key: "地区"
    team:
      source_key: "制作组"

  title_components:
    title:
      source_key: "主标题"
    season_episode:
      source_key: "季集"
    year:
      source_key: "年份"
    status:
      source_key: "剧集状态"
    edition:
      source_key: "发布版本"
    resolution:
      source_key: "分辨率"
    platform:
      source_key: "片源平台"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    video_format:
      source_key: "视频格式"
    hdr_format:
      source_key: "HDR格式"
    bit_depth:
      source_key: "色深"
    frame_rate:
      source_key: "帧率"
    audio_codec:
      source_key: "音频编码"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  # 将站点下拉菜单的文本映射到全局标准化键
  standard_keys:
    type:
      "Movies/电影": "category.movie"
      "TV Series/电视剧": "category.tv_series"
      "TV Shows/综艺": "category.tv_shows"
      "Documentaries/纪录片": "category.documentaries"
      "Animations/动漫、动画": "category.animation"
      "Music Videos/音乐视频": "category.music_video"
      "Sports/体育": "category.sports"
      "Music/音乐": "category.music"
      "Others/其他": "category.other"

    medium:
      "WEB-DL": "medium.webdl"
      "HDTV": "medium.hdtv"
      "DVD": "medium.dvd"
      "CD": "medium.cd"
      "SACD": "medium.sacd" # 自定义标准键
      "CD+VCD": "medium.cd_vcd" # 自定义标准键
      "CD+DVD": "medium.cd_dvd" # 自定义标准键
      "黑胶": "medium.vinyl" # 自定义标准键
      "UHD原盘": "medium.uhd_bluray"
      "Other/其他": "medium.other"
      "UHD DIY": "medium.uhd_diy" # 自定义标准键
      "UHD Remux": "medium.remux" # 视为UHD Remux
      "UHD压制": "medium.encode" # 视为UHD Encode
      "BD原盘": "medium.bluray"
      "BD DIY": "medium.bluray_diy" # 自定义标准键
      "BD Remux": "medium.remux"
      "1080P/i压制": "medium.encode"
      "720P压制": "medium.encode"
      "MiniSD": "medium.minisd" # 自定义标准键

    video_codec:
      "MPEG-2": "video.mpeg2"
      "MPEG-4": "video.mpeg4" # 自定义标准键
      "Xvid": "video.xvid"
      "AV1": "video.av1"
      "Other/其他": "video.other"
      "VC-1": "video.vc1"
      "x265": "video.x265"
      "H.265/HEVC": "video.h265"
      "x264": "video.h264"
      "H.264/AVC": "video.h264"

    audio_codec:
      "DDP Atmos": "audio.ddp_atmos" # 自定义标准键
      "TrueHD Atmos": "audio.truehd_atmos"
      "DTS:X": "audio.dtsx"
      "True-HD": "audio.truehd"
      "DTS-HDMA": "audio.dts_hd_ma"
      "DTS-HD HR": "audio.dts_hd_hr"
      "DTS": "audio.dts"
      "LPCM": "audio.lpcm"
      "WAV": "audio.wav"
      "APE": "audio.ape"
      "FLAC": "audio.flac"
      "DSD": "audio.dsd" # 自定义标准键
      "AAC": "audio.aac"
      "DDP/DD+/EAC3": "audio.ddp"
      "Dolby Digital/DD": "audio.ac3"
      "MPEG": "audio.mpeg"
      "OGG": "audio.ogg"
      "Other/其他": "audio.other"
      "m4a": "audio.m4a"
      "ALAC": "audio.alac" # 自定义标准键
      "MP3": "audio.mp3"
      "TTA": "audio.tta" # 自定义标准键
      "AC3": "audio.ac3"

    resolution:
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "Other/其他": "resolution.other"
      "4K/UHD/2160P": "resolution.r2160p"
      "8K/4320P": "resolution.r4320p"

    source:
      "MY/马来西亚": "source.malaysia" # 自定义标准键
      "Other/其他": "source.other"
      "SG/新加坡": "source.singapore" # 自定义标准键
      "IN/印度": "source.india"
      "KR/韩国": "source.korea"
      "JP/日本": "source.japan"
      "UK/英国": "source.uk"
      "EU/欧洲": "source.europe"
      "US/美国": "source.usa"
      "TW/台湾": "source.taiwan"
      "HK/香港": "source.hongkong"
      "CN/中国大陆": "source.china"

    team:
      "HDHome": "team.hdhome"
      "HDFans": "team.hdfans"
      "CHDBits": "team.chdbits"
      "HDC": "team.hdc"
      "TTG": "team.ttg"
      "WiKi": "team.wiki"
      "beAst": "team.beast"
      "CMCT": "team.cmct"
      "FRDS": "team.frds"
      "HDS": "team.hds"
      "OurBits": "team.ourbits"
      "PTer": "team.pter"
      "Audies": "team.audies"
      "Ubits": "team.ubits"
      "HHClub": "team.hhclub"
      "DIC": "team.dic"
      "PTHome": "team.pthome"
      "QHstudIo": "team.qhstudio"
      "Hares": "team.hares"
      "TLF": "team.tlf"
      "PTP": "team.ptp"
      "BTN/NTb": "team.btn"
      "EPSiLON": "team.epsilon"
      "FraMeSToR": "team.framestor"
      "OpenCD": "team.opencd"
      "Other/其他": "team.other"
      "LemonHD": "team.lemonhd"
      "GGN": "team.ggn"
      "Red": "team.red"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数值
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.music_video": "406"
    "category.sports": "407"
    "category.music": "408"
    "category.other": "409"
    "default": "409"

  medium:
    "medium.webdl": "9"
    "medium.hdtv": "8"
    "medium.dvd": "6"
    "medium.cd": "5"
    "medium.sacd": "4"
    "medium.cd_vcd": "7"
    "medium.cd_dvd": "3"
    "medium.vinyl": "2"
    "medium.uhd_bluray": "19"
    "medium.other": "1"
    "medium.uhd_diy": "18"
    "medium.remux": "13" # BD Remux 和 UHD Remux 都映射到 Remux
    "medium.encode": "12" # 1080p/i 和 UHD 压制都映射到 Encode
    "medium.bluray": "15"
    "medium.bluray_diy": "14"
    "medium.minisd": "10"
    "default": "1"

  video_codec:
    "video.mpeg2": "1"
    "video.mpeg4": "2"
    "video.xvid": "3"
    "video.av1": "4"
    "video.other": "5"
    "video.vc1": "6"
    "video.x265": "7"
    "video.h265": "8"
    "video.h264": "10" # x264和H.264都映射到此
    "default": "5"

  audio_codec:
    "audio.ddp_atmos": "12"
    "audio.truehd_atmos": "23"
    "audio.dtsx": "22"
    "audio.truehd": "21"
    "audio.dts_hd_ma": "20"
    "audio.dts_hd_hr": "19"
    "audio.dts": "18"
    "audio.lpcm": "17"
    "audio.wav": "16"
    "audio.ape": "15"
    "audio.flac": "14"
    "audio.dsd": "13"
    "audio.aac": "1"
    "audio.ddp": "11"
    "audio.ac3": "10" # Dolby Digital/DD 和 AC3
    "audio.mpeg": "9"
    "audio.ogg": "8"
    "audio.other": "7"
    "audio.m4a": "6"
    "audio.alac": "5"
    "audio.mp3": "4"
    "audio.tta": "3"
    "default": "7"

  resolution:
    "resolution.r1080p": "1"
    "resolution.r1080i": "2"
    "resolution.r720p": "3"
    "resolution.sd": "4"

    "resolution.other": "5"
    "resolution.r2160p": "6"
    "resolution.r4320p": "7"
    "default": "5"

  source:
    "source.malaysia": "1"
    "source.other": "2"
    "source.singapore": "3"
    "source.india": "4"
    "source.korea": "5"
    "source.japan": "6"
    "source.uk": "7"
    "source.europe": "8"
    "source.usa": "9"
    "source.taiwan": "10"
    "source.hongkong": "11"
    "source.china": "12"
    "default": "2"

  team:
    "team.hdhome": "15"
    "team.hdfans": "29"
    "team.chdbits": "28"
    "team.hdc": "27"
    "team.ttg": "26"
    "team.wiki": "25"
    "team.beast": "24"
    "team.cmct": "23"
    "team.frds": "22"
    "team.hds": "21"
    "team.ourbits": "20"
    "team.pter": "19"
    "team.audies": "18"
    "team.ubits": "17"
    "team.hhclub": "16"
    "team.dic": "1"
    "team.pthome": "14"
    "team.qhstudio": "13"
    "team.hares": "12"
    "team.tlf": "11"
    "team.ptp": "10"
    "team.btn": "9"
    "team.epsilon": "8"
    "team.framestor": "7"
    "team.opencd": "6"
    "team.other": "5"
    "team.lemonhd": "4"
    "team.ggn": "3"
    "team.red": "2"
    "default": "5"

  tag:
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "tag.保种": 21
    "tag.AI修复": 20
    "tag.刮削": 19
    "tag.完结": 18
    "tag.Hi-Res": 17
    "tag.8K": 16
    "tag.4K": 15
    "tag.Atmos": 14
    "tag.Dolby_Vision": 13
    "tag.特效": 12
    "tag.中英双语": 11
    "tag.源站转发": 10
    "tag.原创": 9
    "tag.微光星辰": 8
    "default": null
